version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: queue-system-db
    environment:
      POSTGRES_DB: queue_system
      POSTGRES_USER: queue
      POSTGRES_PASSWORD: system
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: